apiVersion: v1
kind: Namespace
metadata:
  name: sul
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: sul
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q= #guest
  RABBIT_PASSWORD: Z3Vlc3Q= #guest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-sul
  namespace: sul
  labels:
    app: coffee-sul
spec:
  selector:
    matchLabels:
      app: coffee-sul
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-sul
    spec:
      containers:
      - name: coffee-sul
        image: coffee-sul:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBIT_USERNAME
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBIT_PASSWORD