apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q= #guest
  RABBIT_PASSWORD: Z3Vlc3Q= #guest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bachelor-sul
  labels:
    app: bachelor-sul
spec:
  selector:
    matchLabels:
      app: bachelor-sul
  replicas: 1
  template:
    metadata:
      labels:
        app: bachelor-sul
    spec:
      containers:
      - name: bachelor-sul
        image: jsaev/bachelor-sul:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBIT_USERNAME
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBIT_PASSWORD